version: '2'
services:
    appserver1:
        build: .
        command: dev
        volumes:
            - "./:/app"
        depends_on:
            - "db"

    appserver2:
        build: .
        command: dev
        volumes:
            - "./:/app"
        depends_on:
            - "appserver1"

    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=waecm
            - MYSQL_USER=waecmuser
            - MYSQL_PASSWORD=waecmpassword
            - MYSQL_ROOT_HOST=%

    loadbalancer:
        image: nginx:stable-alpine
        ports:
            - "8080:443"
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        depends_on:
            - "appserver2"

    # monitoring:
        # image: ./monitoring/.
