version: '2'
services:
    appserver1:
        build: .
        command: deploy
        volumes:
            - "./:/app"
        depends_on:
            - "db"

    appserver2:
        build: .
        command: deploy
        volumes:
            - "./:/app"
        depends_on:
            - "appserver1"

    db:
        build: ./db
        ports:
            - "3306:3306"

    loadbalancer:
        image: nginx:stable-alpine
        ports:
            - "8080:443"
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        depends_on:
            - "appserver2"

    # monitoring:
        # image: ./monitoring/.
