version: '2'
services:
    appserver1:
        build: .
        command: dev 
        volumes:
            - "./:/app"
        depends_on:
            - "db"
        ports:
            - "3001:3001"
        environment:
            - APPSERVER=1

    appserver2:
        build: .
        command: dev
        volumes:
            - "./:/app"
        depends_on:
            - "appserver1"
        ports:
            - "3002:3002"
        environment:
            - APPSERVER=2
    db:
        build: ./db
        command: dev
        ports:
            - "3306:3306"
            - "3000:3000"

    loadbalancer:
        image: nginx:stable-alpine
        ports:
            - "8080:443"
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        depends_on:
            - "appserver2"

    # monitoring:
        # image: ./monitoring/.
