version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=GH45hejg0ehg3h408gh430hg324h
      - MYSQL_DATABASE=waecm
      - MYSQL_USER=waecmuser
      - MYSQL_PASSWORD=Fcgdaeb1726
