version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=waecm
      - MYSQL_USER=waecmuser
      - MYSQL_PASSWORD=waecmpassword
  webapp:
    build: .
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    links:
      - mysql:db